export class User {
  constructor(
    public id: number,
    public name: string,
    public email: string,
    public password_hash?: string,
    public google_id?: string,
    public facebook_id?: string,
    public provider: "local" | "google" | "facebook" | "apple" = "local",
    public gender?: "male" | "female" | "other",
    public age?: number,
    public location?: string,
    public bio?: string,
    public interestsTags?: string[],
    public avatar_url?: string,
    public photos?: string[],
    public lookingFor?: "friendship" | "relationship" | "marriage" | "casual",
    public occupation?: string,
    public education?: string,
    public is_verified: boolean = false,
    public violation_count: number = 0,
    public chat_ban_until?: Date,
    public is_chat_locked: boolean = false,
    public is_active: boolean = true,
    public role: "user" | "admin" | "moderator" = "user",
    public subscription_plan: "free" | "premium" | "vip" = "free",
    public subscription_expires?: Date,
    public email_verified: boolean = false,
    public verification_token?: string,
    public verification_expires?: Date,
    public access_token?: string,
    public refresh_token?: string,
    public last_login_at?: Date,
    public created_at?: Date,
    public updated_at?: Date,
  ) {}
}
